FROM linuxserver/wireguard:latest

RUN apt update && apt install -y curl
RUN curl -O https://packages.microsoft.com/config/debian/10/packages-microsoft-prod.deb && \
	dpkg -i packages-microsoft-prod.deb && \
	apt update && \
	apt install -y powershell && \
	apt install -y nano && \
	apt update && \
	rm -rf packages-microsoft-prod.deb

SHELL ["pwsh", "-c"]
RUN echo "Set-Alias Add-UserWG /scripts/add-user-wg.ps1" >> $profile.AllUsersAllHosts